@echo off
REM DacatDHCP Build Script
REM Requires: Go 1.26.4
REM Prerequisite: cmd\dacatdhcp\rsrc_windows_amd64.syso must exist (generated by generate_resource.bat)
REM Output: dist\DacatDHCP.exe + dist\DacatDHCP-v<version>-windows-amd64.zip
REM Version source: internal\version\versioninfo.json (PowerShell validates EXE VersionInfo against it)
REM Script does not depend on current working directory, uses ROOT to locate project root

setlocal EnableExtensions EnableDelayedExpansion
set "EXITCODE=0"

REM Locate project root (script is in scripts\, root is %~dp0..)
set "ROOT=%~dp0.."
pushd "%ROOT%" || ( set "EXITCODE=1" & goto :cleanup )

echo === DacatDHCP Build ===

REM Step 1: Validate Go version is 1.26.4
echo [1/7] Validating Go version...
for /f "tokens=3" %%v in ('go version 2^>nul') do set GOVER=%%v
if "!GOVER!"=="" (
    echo ERROR: Go is not installed or not in PATH.
    set "EXITCODE=1"
    goto :cleanup
)
set GOVER=!GOVER:go=!
if not "!GOVER!"=="1.26.4" (
    echo ERROR: Go version must be exactly 1.26.4, but found !GOVER!.
    echo Please install Go 1.26.4 from https://go.dev/dl/
    set "EXITCODE=1"
    goto :cleanup
)
echo Go version !GOVER! validated.

REM Step 2: Check PE resource file exists
echo [2/7] Checking PE resource...
if not exist "cmd\dacatdhcp\rsrc_windows_amd64.syso" (
    echo ERROR: cmd\dacatdhcp\rsrc_windows_amd64.syso not found.
    echo Run scripts\generate_resource.bat first to generate it.
    set "EXITCODE=1"
    goto :cleanup
)

REM Step 3: Check gofmt (recursively check all *.go files)
echo [3/7] Checking gofmt...
set "FMT_ISSUES="
for /f "delims=" %%f in ('gofmt -l .\cmd .\internal .\web .\tests 2^>nul') do (
    echo ERROR: Unformatted file: %%f
    echo Run: gofmt -w %%f
    set "FMT_ISSUES=1"
    set "EXITCODE=1"
)
if defined FMT_ISSUES (
    echo ERROR: gofmt found unformatted files. Fix with gofmt -w before building.
    goto :cleanup
)

REM Step 4: Run go vet
echo [4/7] Running go vet...
go vet ./...
if errorlevel 1 (
    echo ERROR: go vet failed
    set "EXITCODE=!ERRORLEVEL!"
    if "!EXITCODE!"=="0" set "EXITCODE=1"
    goto :cleanup
)

REM Step 5: Run tests
echo [5/7] Running tests...
go test ./... -count=1
if errorlevel 1 (
    echo ERROR: go test failed
    set "EXITCODE=!ERRORLEVEL!"
    if "!EXITCODE!"=="0" set "EXITCODE=1"
    goto :cleanup
)

REM Step 6: Build final EXE (GUI subsystem: no CMD window), output to dist directory
echo [6/7] Building dist\DacatDHCP.exe...
if not exist "dist" mkdir "dist"
set CGO_ENABLED=0
set GOOS=windows
set GOARCH=amd64
go build -ldflags="-H=windowsgui" -o "dist\DacatDHCP.exe" ./cmd/dacatdhcp/
if errorlevel 1 (
    echo ERROR: go build failed
    set "EXITCODE=!ERRORLEVEL!"
    if "!EXITCODE!"=="0" set "EXITCODE=1"
    goto :cleanup
)

REM Step 7: Validate EXE VersionInfo + Generate release ZIP
echo [7/7] Validating VersionInfo and generating release ZIP...
if not exist "dist\DacatDHCP.exe" (
    echo ERROR: Build artifact dist\DacatDHCP.exe not found.
    set "EXITCODE=1"
    goto :cleanup
)

REM Single PowerShell block: VersionInfo validation + ZIP generation + ZIP content verification
REM - $ErrorActionPreference='Stop': any failure returns non-0
REM - Pre-check all 4 source files exist before compressing
REM - Generate temp ZIP first, atomic rename to final ZIP on success
REM - Re-read ZIP and verify exactly 4 files at root level
REM - Clean up temp files on any failure
REM - Version number read from internal\version\versioninfo.json (single source, no hardcoding)
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
 "$ErrorActionPreference='Stop';" ^
 "$j=Get-Content 'internal\version\versioninfo.json' -Raw -Encoding UTF8|ConvertFrom-Json;" ^
 "$v=(Get-Item 'dist\DacatDHCP.exe').VersionInfo;" ^
 "$ok=$true;" ^
 "$pvStr=$j.StringFileInfo.ProductVersion;" ^
 "$pvBin=($j.FixedFileInfo.ProductVersion.Major.ToString()+'.'+$j.FixedFileInfo.ProductVersion.Minor.ToString()+'.'+$j.FixedFileInfo.ProductVersion.Patch.ToString()+'.'+$j.FixedFileInfo.ProductVersion.Build.ToString());" ^
 "if([string]::IsNullOrEmpty($v.FileDescription) -or $v.FileDescription -ne $j.StringFileInfo.FileDescription){Write-Host '  FAIL: FileDescription';$ok=$false};" ^
 "if([string]::IsNullOrEmpty($v.FileVersion) -or $v.FileVersion -ne $j.StringFileInfo.FileVersion){Write-Host '  FAIL: FileVersion';$ok=$false};" ^
 "if([string]::IsNullOrEmpty($v.ProductName) -or $v.ProductName -ne $j.StringFileInfo.ProductName){Write-Host '  FAIL: ProductName';$ok=$false};" ^
 "if([string]::IsNullOrEmpty($v.ProductVersion) -or ($v.ProductVersion -ne $pvStr -and $v.ProductVersion -ne $pvBin)){Write-Host '  FAIL: ProductVersion';$ok=$false};" ^
 "if([string]::IsNullOrEmpty($v.CompanyName) -or $v.CompanyName -ne $j.StringFileInfo.CompanyName){Write-Host '  FAIL: CompanyName';$ok=$false};" ^
 "if([string]::IsNullOrEmpty($v.LegalCopyright) -or $v.LegalCopyright -ne $j.StringFileInfo.LegalCopyright){Write-Host '  FAIL: LegalCopyright';$ok=$false};" ^
 "if([string]::IsNullOrEmpty($v.OriginalFilename) -or $v.OriginalFilename -ne $j.StringFileInfo.OriginalFilename){Write-Host '  FAIL: OriginalFilename';$ok=$false};" ^
 "if(-not $ok){Write-Host 'ERROR: VersionInfo validation failed.';exit 1};" ^
 "Write-Host 'VersionInfo validation passed.';" ^
 "$ver=$j.StringFileInfo.ProductVersion;" ^
 "$finalZip='dist\DacatDHCP-v'+$ver+'-windows-amd64.zip';" ^
 "$tmpZip='dist\DacatDHCP-v'+$ver+'-windows-amd64.tmp.zip';" ^
 "$tmpDir='dist\_zip_tmp';" ^
 "try{" ^
 "  if(Test-Path $tmpDir){Remove-Item $tmpDir -Recurse -Force};" ^
 "  if(Test-Path $tmpZip){Remove-Item $tmpZip -Force};" ^
 "  @('dist\DacatDHCP.exe','LICENSE','NOTICE','TRADEMARKS.md')|ForEach-Object{if(-not(Test-Path $_)){Write-Host ('ERROR: Required file not found: '+$_);exit 1}};" ^
 "  New-Item -ItemType Directory -Path $tmpDir -Force|Out-Null;" ^
 "  Copy-Item 'dist\DacatDHCP.exe' $tmpDir;" ^
 "  Copy-Item 'LICENSE' $tmpDir;" ^
 "  Copy-Item 'NOTICE' $tmpDir;" ^
 "  Copy-Item 'TRADEMARKS.md' $tmpDir;" ^
 "  Compress-Archive -Path ($tmpDir+'\*') -DestinationPath $tmpZip -Force;" ^
 "  $archive=[System.IO.Compression.ZipFile]::OpenRead((Resolve-Path $tmpZip).Path);" ^
 "  $names=@($archive.Entries|ForEach-Object{$_.FullName});" ^
 "  $archive.Dispose();" ^
 "  $expected=@('DacatDHCP.exe','LICENSE','NOTICE','TRADEMARKS.md');" ^
 "  $missing=$expected|Where-Object{$names -notcontains $_};" ^
 "  if($missing){Write-Host('ERROR: ZIP missing files: '+($missing -join ', '));exit 1};" ^
 "  $extra=$names|Where-Object{$expected -notcontains $_};" ^
 "  if($extra){Write-Host('ERROR: ZIP contains extra entries: '+($extra -join ', '));exit 1};" ^
 "  Move-Item -Path $tmpZip -Destination $finalZip -Force;" ^
 "  Write-Host ('Release ZIP: '+$finalZip);" ^
 "}finally{" ^
 "  if(Test-Path $tmpDir){Remove-Item $tmpDir -Recurse -Force};" ^
 "  if(Test-Path $tmpZip){Remove-Item $tmpZip -Force};" ^
 "}"
if errorlevel 1 (
    echo ERROR: VersionInfo validation or release ZIP generation failed.
    set "EXITCODE=!ERRORLEVEL!"
    if "!EXITCODE!"=="0" set "EXITCODE=1"
    goto :cleanup
)

echo === Build Complete: dist\DacatDHCP.exe + release ZIP ===

:cleanup
popd
endlocal & exit /b %EXITCODE%
