@echo off
REM DacatDHCP Build Script
REM Requires: Go 1.26.4
REM Prerequisite: cmd\dacatdhcp\rsrc_windows_amd64.syso must exist (generated by generate_resource.bat)
REM Output: dist\DacatDHCP.exe with PE icon+VERSIONINFO resource, GUI subsystem (no CMD window)
REM Version source: internal\version\versioninfo.json (PowerShell validates EXE VersionInfo against it)
REM Script does not depend on current working directory, uses ROOT to locate project root

setlocal EnableExtensions EnableDelayedExpansion
set "EXITCODE=0"

REM Locate project root (script is in scripts\, root is %~dp0..)
set "ROOT=%~dp0.."
pushd "%ROOT%" || ( set "EXITCODE=1" & goto :cleanup )

echo === DacatDHCP Build ===

REM 0. Validate Go version is 1.26.4
echo [0/7] Validating Go version...
for /f "tokens=3" %%v in ('go version 2^>nul') do set GOVER=%%v
if "!GOVER!"=="" (
    echo ERROR: Go is not installed or not in PATH.
    set "EXITCODE=1"
    goto :cleanup
)
set GOVER=!GOVER:go=!
if not "!GOVER!"=="1.26.4" (
    echo ERROR: Go version must be exactly 1.26.4, but found !GOVER!.
    echo Please install Go 1.26.4 from https://go.dev/dl/
    set "EXITCODE=1"
    goto :cleanup
)
echo Go version !GOVER! validated.

REM 1. Check PE resource file exists
echo [1/7] Checking PE resource...
if not exist "cmd\dacatdhcp\rsrc_windows_amd64.syso" (
    echo ERROR: cmd\dacatdhcp\rsrc_windows_amd64.syso not found.
    echo Run scripts\generate_resource.bat first to generate it.
    set "EXITCODE=1"
    goto :cleanup
)

REM 2. Check gofmt (no unformatted files allowed)
echo [2/7] Checking gofmt...
for /f "delims=" %%f in ('gofmt -l . 2^>nul') do (
    echo ERROR: Unformatted file: %%f
    echo Run: gofmt -w %%f
    set "EXITCODE=1"
)
if !EXITCODE! neq 0 (
    echo ERROR: gofmt found unformatted files. Fix with gofmt -w before building.
    goto :cleanup
)

REM 3. Run go vet
echo [3/7] Running go vet...
go vet ./...
if errorlevel 1 (
    echo ERROR: go vet failed
    set "EXITCODE=!ERRORLEVEL!"
    if "!EXITCODE!"=="0" set "EXITCODE=1"
    goto :cleanup
)

REM 4. Run tests
echo [4/7] Running tests...
go test ./... -count=1
if errorlevel 1 (
    echo ERROR: go test failed
    set "EXITCODE=!ERRORLEVEL!"
    if "!EXITCODE!"=="0" set "EXITCODE=1"
    goto :cleanup
)

REM 5. Build final EXE (GUI subsystem: no CMD window), output to dist directory
echo [5/7] Building dist\DacatDHCP.exe...
if not exist "dist" mkdir "dist"
set CGO_ENABLED=0
set GOOS=windows
set GOARCH=amd64
go build -ldflags="-H=windowsgui" -o "dist\DacatDHCP.exe" ./cmd/dacatdhcp/
if errorlevel 1 (
    echo ERROR: go build failed
    set "EXITCODE=!ERRORLEVEL!"
    if "!EXITCODE!"=="0" set "EXITCODE=1"
    goto :cleanup
)

REM 6. Validate EXE VersionInfo against versioninfo.json (single version source)
echo [6/7] Validating EXE VersionInfo...
if not exist "dist\DacatDHCP.exe" (
    echo ERROR: Build artifact dist\DacatDHCP.exe not found.
    set "EXITCODE=1"
    goto :cleanup
)
REM All expected values are read from internal\version\versioninfo.json, no hardcoding in build.bat
powershell -NoProfile -ExecutionPolicy Bypass -Command "$j=Get-Content 'internal\version\versioninfo.json' -Raw -Encoding UTF8|ConvertFrom-Json; $v=(Get-Item 'dist\DacatDHCP.exe').VersionInfo; $ok=$true; $pvStr=$j.StringFileInfo.ProductVersion; $pvBin=($j.FixedFileInfo.ProductVersion.Major.ToString()+'.'+$j.FixedFileInfo.ProductVersion.Minor.ToString()+'.'+$j.FixedFileInfo.ProductVersion.Patch.ToString()+'.'+$j.FixedFileInfo.ProductVersion.Build.ToString()); if([string]::IsNullOrEmpty($v.FileDescription) -or $v.FileDescription -ne $j.StringFileInfo.FileDescription){Write-Host '  FAIL: FileDescription';$ok=$false}; if([string]::IsNullOrEmpty($v.FileVersion) -or $v.FileVersion -ne $j.StringFileInfo.FileVersion){Write-Host '  FAIL: FileVersion';$ok=$false}; if([string]::IsNullOrEmpty($v.ProductName) -or $v.ProductName -ne $j.StringFileInfo.ProductName){Write-Host '  FAIL: ProductName';$ok=$false}; if([string]::IsNullOrEmpty($v.ProductVersion) -or ($v.ProductVersion -ne $pvStr -and $v.ProductVersion -ne $pvBin)){Write-Host '  FAIL: ProductVersion';$ok=$false}; if([string]::IsNullOrEmpty($v.CompanyName) -or $v.CompanyName -ne $j.StringFileInfo.CompanyName){Write-Host '  FAIL: CompanyName';$ok=$false}; if([string]::IsNullOrEmpty($v.LegalCopyright) -or $v.LegalCopyright -ne $j.StringFileInfo.LegalCopyright){Write-Host '  FAIL: LegalCopyright';$ok=$false}; if([string]::IsNullOrEmpty($v.OriginalFilename) -or $v.OriginalFilename -ne $j.StringFileInfo.OriginalFilename){Write-Host '  FAIL: OriginalFilename';$ok=$false}; if(-not $ok){Write-Host 'ERROR: VersionInfo validation failed. See FAIL messages above.';exit 1}; Write-Host 'VersionInfo validation passed.'"
if errorlevel 1 (
    echo ERROR: VersionInfo validation failed. EXE must not be released.
    set "EXITCODE=!ERRORLEVEL!"
    if "!EXITCODE!"=="0" set "EXITCODE=1"
    goto :cleanup
)

REM 7. Generate release ZIP (DacatDHCP.exe + LICENSE + NOTICE + TRADEMARKS.md)
echo [7/7] Generating release ZIP...
REM Version number read from internal\version\versioninfo.json (single version source, no hardcoding)
powershell -NoProfile -ExecutionPolicy Bypass -Command "$j=Get-Content 'internal\version\versioninfo.json' -Raw -Encoding UTF8|ConvertFrom-Json; $ver=$j.StringFileInfo.ProductVersion; $zip='dist\DacatDHCP-v'+$ver+'-windows-amd64.zip'; $tmp='dist\_zip_tmp'; if(Test-Path $tmp){Remove-Item $tmp -Recurse -Force}; New-Item -ItemType Directory -Path $tmp -Force|Out-Null; Copy-Item 'dist\DacatDHCP.exe' $tmp; Copy-Item 'LICENSE' $tmp; Copy-Item 'NOTICE' $tmp; Copy-Item 'TRADEMARKS.md' $tmp; if(Test-Path $zip){Remove-Item $zip -Force}; Compress-Archive -Path ($tmp+'\*') -DestinationPath $zip -Force; Remove-Item $tmp -Recurse -Force; Write-Host ('Release ZIP: '+$zip)"
if errorlevel 1 (
    echo ERROR: Release ZIP generation failed.
    set "EXITCODE=!ERRORLEVEL!"
    if "!EXITCODE!"=="0" set "EXITCODE=1"
    goto :cleanup
)

echo === Build Complete: dist\DacatDHCP.exe + release ZIP ===

:cleanup
popd
endlocal & exit /b %EXITCODE%
